version: 2.1
jobs:
  test:
    docker:
      - image: maven:3-jdk-8-alpine
    steps:
      - checkout
      - restore_cache:
          key: spigot-starter-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: spigot-starter-{{ checksum "pom.xml" }}
      - run: mvn clean test jacoco:report coveralls:report -Dcoveralls.token=$COVERALLS_TOKEN
  deploy:
    docker:
      - image: maven:3-jdk-8
    steps:
      - checkout
      - run: echo $GPG_SECRET_KEYS | base64 --decode | gpg --batch --import --passphrase $GPG_PASSPHRASE
      - run: echo $GPG_OWNERTRUST | base64 --decode | gpg --batch --import-ownertrust
      - run: mvn --settings .maven.xml clean -Prelease deploy
workflows:
  version: 2
  branch_test:
    jobs:
      - test
  master_deploy:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/